import { Product } from './components/ProductDetail';

export const DETAILED_PRODUCTS: Product[] = [
  {
    id: '1',
    name: "东海航空 拿铁咖啡 (Latte)",
    images: ["https://picsum.photos/seed/latte/800/800"],
    price: 28,
    originalPrice: 32,
    sales: 1205,
    rating: 99,
    stock: 100,
    description: "精选阿拉比卡咖啡豆，搭配鲜牛乳，口感丝滑，浓郁醇香。",
    specs: [
      { label: '规格', options: ['标准杯', '大杯'] },
      { label: '温度', options: ['热', '冰'] }
    ],
    afterSales: "饮品类商品建议即时饮用，非质量问题不支持退换。",
    category: "咖啡饮品",
    tag: "人气推荐"
  },
  {
    id: '2',
    name: "东海航空 美式咖啡 (Americano)",
    images: ["https://picsum.photos/seed/americano/800/800"],
    price: 22,
    originalPrice: 26,
    sales: 3500,
    rating: 98,
    stock: 200,
    description: "经典美式，保留咖啡最原始的香气，提神醒脑，低脂健康。",
    specs: [
      { label: '规格', options: ['标准杯', '大杯'] },
      { label: '温度', options: ['热', '冰'] }
    ],
    afterSales: "饮品类商品建议即时饮用。",
    category: "咖啡饮品",
    tag: "清爽提神"
  },
  {
    id: '3',
    name: "精选茗茶 魔力普尔 (Magic Pu'er)",
    images: ["https://picsum.photos/seed/puer/800/800"],
    price: 68,
    originalPrice: 88,
    sales: 890,
    rating: 97,
    stock: 50,
    description: "云南大叶种晒青毛茶，经特殊工艺发酵，汤色红浓，陈香显著。",
    specs: [
      { label: '包装', options: ['罐装 100g', '礼盒装 250g'] }
    ],
    afterSales: "食品类商品非质量问题不支持退换。",
    category: "精选茗茶",
    tag: "陈年醇香"
  },
  {
    id: '4',
    name: "精选茗茶 玫瑰滇红 (Rose Dianhong)",
    images: ["https://picsum.photos/seed/tea/800/800"],
    price: 58,
    originalPrice: 78,
    sales: 450,
    rating: 96,
    stock: 100,
    description: "滇红红茶融合天然玫瑰花瓣，花香与茶香交织，口感甜润。",
    specs: [
      { label: '包装', options: ['罐装 100g', '礼盒装 200g'] }
    ],
    afterSales: "食品类商品非质量问题不支持退换。",
    category: "精选茗茶",
    tag: "花香四溢"
  },
  {
    id: '5',
    name: "东海航空 熊猫玩偶 (Panda Plush)",
    images: ["https://picsum.photos/seed/panda/800/800"],
    price: 88,
    originalPrice: 128,
    sales: 2100,
    rating: 99,
    stock: 150,
    description: "东海航空定制熊猫玩偶，身穿飞行员制服，材质柔软，萌趣可爱。",
    specs: [
      { label: '尺寸', options: ['25cm', '40cm'] }
    ],
    afterSales: "支持7天无理由退换。",
    category: "航空周边",
    tag: "萌物推荐"
  },
  {
    id: '6',
    name: "东海航空 飞行员太阳镜 (Sunglasses)",
    images: ["https://picsum.photos/seed/sunglasses/800/800"],
    price: 158,
    originalPrice: 258,
    sales: 1560,
    rating: 98,
    stock: 300,
    description: "经典飞行员框型，偏光镜片，防紫外线，帅气出行必备。",
    specs: [
      { label: '颜色', options: ['经典黑', '气质银', '深海蓝'] }
    ],
    afterSales: "支持7天无理由退换。",
    category: "航空周边",
    tag: "酷飒出行"
  },
  {
    id: '7',
    name: "东海航空 波音737-800 飞机模型",
    images: ["https://picsum.photos/seed/model/800/800"],
    price: 198,
    originalPrice: 298,
    sales: 800,
    rating: 99,
    stock: 50,
    description: "1:200比例合金模型，细节还原度高，东海航空官方涂装。",
    specs: [
      { label: '比例', options: ['1:200', '1:400'] }
    ],
    afterSales: "支持7天无理由退换。",
    category: "航空周边",
    tag: "收藏必备"
  },
  {
    id: '8',
    name: "东海航空 定制钥匙扣 (Keychain)",
    images: ["https://picsum.photos/seed/key/800/800"],
    price: 35,
    originalPrice: 45,
    sales: 5000,
    rating: 98,
    stock: 1000,
    description: "锌合金材质，精致Logo，耐磨耐用，航空情怀随身带。",
    specs: [
      { label: '款式', options: ['飞机款', 'Logo款'] }
    ],
    afterSales: "支持7天无理由退换。",
    category: "航空周边",
    tag: "精致小巧"
  },
  {
    id: '9',
    name: "东海航空 创意冰箱贴 (Fridge Magnet)",
    images: ["https://picsum.photos/seed/magnet/800/800"],
    price: 25,
    originalPrice: 35,
    sales: 3200,
    rating: 97,
    stock: 800,
    description: "硅胶材质，3D立体浮雕效果，记录每一次精彩飞行。",
    specs: [
      { label: '款式', options: ['地标系列', '飞机系列'] }
    ],
    afterSales: "支持7天无理由退换。",
    category: "航空周边",
    tag: "生活点缀"
  }
];

export const POINTS_PRODUCTS: Product[] = [
  {
    id: 'P1',
    name: "东海航空 拿铁咖啡 (Latte)",
    images: ["https://picsum.photos/seed/latte/800/800"],
    price: 0,
    points: 2800,
    sales: 1205,
    rating: 4.9,
    stock: 100,
    description: "精选阿拉比卡咖啡豆，搭配鲜牛乳，口感丝滑，浓郁醇香。",
    specs: [{ label: '规格', options: ['标准杯', '大杯'] }],
    afterSales: "饮品类商品建议即时饮用，非质量问题不支持退换。",
    category: "咖啡饮品",
    isPointsOnly: true,
    redemptionRules: "每人限兑5杯/天"
  },
  {
    id: 'P2',
    name: "东海航空 美式咖啡 (Americano)",
    images: ["https://picsum.photos/seed/americano/800/800"],
    price: 0,
    points: 2200,
    sales: 3500,
    rating: 4.8,
    stock: 200,
    description: "经典美式，保留咖啡最原始的香气，提神醒脑，低脂健康。",
    specs: [{ label: '规格', options: ['标准杯', '大杯'] }],
    afterSales: "饮品类商品建议即时饮用。",
    category: "咖啡饮品",
    isPointsOnly: true,
    redemptionRules: "每人限兑5杯/天"
  },
  {
    id: 'P3',
    name: "精选茗茶 魔力普尔 (Magic Pu'er)",
    images: ["https://picsum.photos/seed/puer/800/800"],
    price: 0,
    points: 6800,
    sales: 890,
    rating: 4.7,
    stock: 50,
    description: "云南大叶种晒青毛茶，经特殊工艺发酵，汤色红浓，陈香显著。",
    specs: [{ label: '包装', options: ['罐装 100g'] }],
    afterSales: "食品类商品非质量问题不支持退换。",
    category: "精选茗茶",
    isPointsOnly: true,
    redemptionRules: "每人限兑2罐"
  },
  {
    id: 'P4',
    name: "精选茗茶 玫瑰滇红 (Rose Dianhong)",
    images: ["https://picsum.photos/seed/tea/800/800"],
    price: 0,
    points: 5800,
    sales: 450,
    rating: 4.6,
    stock: 100,
    description: "滇红红茶融合天然玫瑰花瓣，花香与茶香交织，口感甜润。",
    specs: [{ label: '包装', options: ['罐装 100g'] }],
    afterSales: "食品类商品非质量问题不支持退换。",
    category: "精选茗茶",
    isPointsOnly: true,
    redemptionRules: "每人限兑2罐"
  },
  {
    id: 'P5',
    name: "东海航空 熊猫玩偶 (Panda Plush)",
    images: ["https://picsum.photos/seed/panda/800/800"],
    price: 0,
    points: 8800,
    sales: 2100,
    rating: 5.0,
    stock: 150,
    description: "东海航空定制熊猫玩偶，身穿飞行员制服，材质柔软，萌趣可爱。",
    specs: [{ label: '尺寸', options: ['25cm'] }],
    afterSales: "支持7天无理由退换。",
    category: "航空周边",
    isPointsOnly: true,
    redemptionRules: "每人限兑1件"
  },
  {
    id: 'P6',
    name: "东海航空 飞行员太阳镜 (Sunglasses)",
    images: ["https://picsum.photos/seed/sunglasses/800/800"],
    price: 0,
    points: 15800,
    sales: 1560,
    rating: 4.8,
    stock: 300,
    description: "经典飞行员框型，偏光镜片，防紫外线，帅气出行必备。",
    specs: [{ label: '颜色', options: ['经典黑'] }],
    afterSales: "支持7天无理由退换。",
    category: "航空周边",
    isPointsOnly: true,
    redemptionRules: "每人限兑1件"
  },
  {
    id: 'P7',
    name: "东海航空 波音737-800 飞机模型",
    images: ["https://picsum.photos/seed/model/800/800"],
    price: 0,
    points: 19800,
    sales: 800,
    rating: 4.9,
    stock: 50,
    description: "1:200比例合金模型，细节还原度高，东海航空官方涂装。",
    specs: [{ label: '比例', options: ['1:200'] }],
    afterSales: "支持7天无理由退换。",
    category: "航空周边",
    isPointsOnly: true,
    redemptionRules: "每人限兑1件"
  },
  {
    id: 'P8',
    name: "东海航空 定制钥匙扣 (Keychain)",
    images: ["https://picsum.photos/seed/key/800/800"],
    price: 0,
    points: 3500,
    sales: 5000,
    rating: 4.8,
    stock: 1000,
    description: "锌合金材质，精致Logo，耐磨耐用，航空情怀随身带。",
    specs: [{ label: '款式', options: ['飞机款'] }],
    afterSales: "支持7天无理由退换。",
    category: "航空周边",
    isPointsOnly: true,
    redemptionRules: "每人限兑3件"
  },
  {
    id: 'P9',
    name: "东海航空 创意冰箱贴 (Fridge Magnet)",
    images: ["https://picsum.photos/seed/magnet/800/800"],
    price: 0,
    points: 2500,
    sales: 3200,
    rating: 4.7,
    stock: 800,
    description: "硅胶材质，3D立体浮雕效果，记录每一次精彩飞行。",
    specs: [{ label: '款式', options: ['飞机系列'] }],
    afterSales: "支持7天无理由退换。",
    category: "航空周边",
    isPointsOnly: true,
    redemptionRules: "每人限兑5件"
  }
];

export const INTERNAL_PRODUCTS: Product[] = [
  {
    id: 'emp-1',
    name: "【员工内购】东海航空 拿铁咖啡 (Latte)",
    images: ["https://picsum.photos/seed/latte/800/800"],
    price: 15,
    originalPrice: 28,
    sales: 450,
    rating: 99,
    stock: 100,
    description: "员工专享5折优惠。精选阿拉比卡咖啡豆，搭配鲜牛乳。",
    specs: [{ label: '规格', options: ['标准杯', '大杯'] }],
    afterSales: "内购饮品建议即时饮用。",
    category: "咖啡饮品",
    tag: "员工专享",
    isInternal: true
  },
  {
    id: 'emp-2',
    name: "【员工内购】东海航空 美式咖啡 (Americano)",
    images: ["https://picsum.photos/seed/americano/800/800"],
    price: 12,
    originalPrice: 22,
    sales: 120,
    rating: 98,
    stock: 200,
    description: "员工专享5折优惠。经典美式，提神醒脑。",
    specs: [{ label: '规格', options: ['标准杯', '大杯'] }],
    afterSales: "内购饮品建议即时饮用。",
    category: "咖啡饮品",
    tag: "员工专享",
    isInternal: true
  },
  {
    id: 'emp-3',
    name: "【员工内购】精选茗茶 魔力普尔 (Magic Pu'er)",
    images: ["https://picsum.photos/seed/puer/800/800"],
    price: 39,
    originalPrice: 68,
    sales: 890,
    rating: 97,
    stock: 50,
    description: "员工内购特惠。云南大叶种晒青毛茶，陈香显著。",
    specs: [{ label: '包装', options: ['罐装 100g'] }],
    afterSales: "内购商品非质量问题不支持退换。",
    category: "精选茗茶",
    tag: "限时特惠",
    isInternal: true
  },
  {
    id: 'emp-4',
    name: "【员工内购】精选茗茶 玫瑰滇红 (Rose Dianhong)",
    images: ["https://picsum.photos/seed/tea/800/800"],
    price: 35,
    originalPrice: 58,
    sales: 340,
    rating: 96,
    stock: 100,
    description: "员工内购特惠。滇红红茶融合天然玫瑰花瓣。",
    specs: [{ label: '包装', options: ['罐装 100g'] }],
    afterSales: "内购商品非质量问题不支持退换。",
    category: "精选茗茶",
    tag: "限时特惠",
    isInternal: true
  },
  {
    id: 'emp-5',
    name: "【员工内购】东海航空 熊猫玩偶 (Panda Plush)",
    images: ["https://picsum.photos/seed/panda/800/800"],
    price: 49,
    originalPrice: 88,
    sales: 210,
    rating: 99,
    stock: 150,
    description: "员工专享福利。身穿飞行员制服的熊猫玩偶。",
    specs: [{ label: '尺寸', options: ['25cm'] }],
    afterSales: "内购商品非质量问题不支持退换。",
    category: "航空周边",
    tag: "员工福利",
    isInternal: true
  },
  {
    id: 'emp-6',
    name: "【员工内购】东海航空 飞行员太阳镜 (Sunglasses)",
    images: ["https://picsum.photos/seed/sunglasses/800/800"],
    price: 89,
    originalPrice: 158,
    sales: 156,
    rating: 98,
    stock: 300,
    description: "员工专享福利。经典飞行员框型，偏光镜片。",
    specs: [{ label: '颜色', options: ['经典黑'] }],
    afterSales: "内购商品非质量问题不支持退换。",
    category: "航空周边",
    tag: "员工福利",
    isInternal: true
  },
  {
    id: 'emp-7',
    name: "【员工内购】东海航空 波音737-800 飞机模型",
    images: ["https://picsum.photos/seed/model/800/800"],
    price: 128,
    originalPrice: 198,
    sales: 80,
    rating: 99,
    stock: 50,
    description: "员工专享福利。1:200比例合金模型。",
    specs: [{ label: '比例', options: ['1:200'] }],
    afterSales: "内购商品非质量问题不支持退换。",
    category: "航空周边",
    tag: "员工福利",
    isInternal: true
  },
  {
    id: 'emp-8',
    name: "【员工内购】东海航空 定制钥匙扣 (Keychain)",
    images: ["https://picsum.photos/seed/key/800/800"],
    price: 19,
    originalPrice: 35,
    sales: 500,
    rating: 98,
    stock: 1000,
    description: "员工专享福利。精致Logo，耐磨耐用。",
    specs: [{ label: '款式', options: ['飞机款'] }],
    afterSales: "内购商品非质量问题不支持退换。",
    category: "航空周边",
    tag: "员工福利",
    isInternal: true
  },
  {
    id: 'emp-9',
    name: "【员工内购】东海航空 创意冰箱贴 (Fridge Magnet)",
    images: ["https://picsum.photos/seed/magnet/800/800"],
    price: 12,
    originalPrice: 25,
    sales: 320,
    rating: 97,
    stock: 800,
    description: "员工专享福利。硅胶材质，3D立体浮雕效果。",
    specs: [{ label: '款式', options: ['飞机系列'] }],
    afterSales: "内购商品非质量问题不支持退换。",
    category: "航空周边",
    tag: "员工福利",
    isInternal: true
  }
];
